version: "3.8"

services:
  postgres:
    image: postgres:13
    container_name: tarah-db
    environment:
      POSTGRES_USER: tarah_admin
      POSTGRES_PASSWORD: thisIsAdminTarahPassword99
      POSTGRES_DB: tarah_admin_db
    ports: []
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U tarah_admin -d tarah_admin_db"]  # Add database
      interval: 5s
      timeout: 5s
      retries: 10

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: tarah-backend
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - DATABASE_URL=postgresql://tarah_admin:thisIsAdminTarahPassword99@postgres:5432/tarah_admin_db
      - NUMBA_CACHE_DIR=/numba_cache  # Ensure this is set
    volumes:
      - /var/www/tarah_static:/app/static
      - backend-numba-cache:/numba_cache
    ports:
      - "8009:8009"
    user: "1000:1000"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: tarah-frontend
    ports:
      - "8080:80"  # Changed to standard HTTP port

networks:
  tarah-network:
    driver: bridge
    
volumes:
  backend-numba-cache:
  postgres-data: